In [137]:
import pandas as pd
from pandas import DataFrame as df
import itertools
import numpy as np

In [138]:
s = np.array([0,0,1,1,1], dtype=np.byte)
def truthTable(s):
    comb = list(itertools.product(np.array([0,1], dtype=np.byte), repeat=len(s)))
    cols = ["s", "x", "f(x)"]
    table = df()
    table[cols[1]] = [str(a) for a in comb]
    table[cols[0]] = str(s)
    table[cols[2]] = [np.dot(a,s)%2 for a in comb]
    return table
truthTable(s)

                  x            s  f(x)
0   (0, 0, 0, 0, 0)  [0 0 1 1 1]     0
1   (0, 0, 0, 0, 1)  [0 0 1 1 1]     1
2   (0, 0, 0, 1, 0)  [0 0 1 1 1]     1
3   (0, 0, 0, 1, 1)  [0 0 1 1 1]     0
4   (0, 0, 1, 0, 0)  [0 0 1 1 1]     1
5   (0, 0, 1, 0, 1)  [0 0 1 1 1]     0
6   (0, 0, 1, 1, 0)  [0 0 1 1 1]     0
7   (0, 0, 1, 1, 1)  [0 0 1 1 1]     1
8   (0, 1, 0, 0, 0)  [0 0 1 1 1]     0
9   (0, 1, 0, 0, 1)  [0 0 1 1 1]     1
10  (0, 1, 0, 1, 0)  [0 0 1 1 1]     1
11  (0, 1, 0, 1, 1)  [0 0 1 1 1]     0
12  (0, 1, 1, 0, 0)  [0 0 1 1 1]     1
13  (0, 1, 1, 0, 1)  [0 0 1 1 1]     0
14  (0, 1, 1, 1, 0)  [0 0 1 1 1]     0
15  (0, 1, 1, 1, 1)  [0 0 1 1 1]     1
16  (1, 0, 0, 0, 0)  [0 0 1 1 1]     0
17  (1, 0, 0, 0, 1)  [0 0 1 1 1]     1
18  (1, 0, 0, 1, 0)  [0 0 1 1 1]     1
19  (1, 0, 0, 1, 1)  [0 0 1 1 1]     0
20  (1, 0, 1, 0, 0)  [0 0 1 1 1]     1
21  (1, 0, 1, 0, 1)  [0 0 1 1 1]     0
22  (1, 0, 1, 1, 0)  [0 0 1 1 1]     0
23  (1, 0, 1, 1, 1)  [0 0 1 1 1]     1
24  (1, 1, 0, 0, 0)  [0 0 1 1 1]     0
25  (1, 1, 0, 0, 1)  [0 0 1 1 1]     1
26  (1, 1, 0, 1, 0)  [0 0 1 1 1]     1
27  (1, 1, 0, 1, 1)  [0 0 1 1 1]     0
28  (1, 1, 1, 0, 0)  [0 0 1 1 1]     1
29  (1, 1, 1, 0, 1)  [0 0 1 1 1]     0
30  (1, 1, 1, 1, 0)  [0 0 1 1 1]     0
31  (1, 1, 1, 1, 1)  [0 0 1 1 1]     1

In [139]:
def bernsteinVazirani(bits):
    s = np.random.choice([0,1], size=bits)
    print(f"s={s}")
    return lambda x: np.dot([np.byte(c) for c in x], s) % 2

In [140]:
f = bernsteinVazirani(5)

s=[0 0 1 0 1]

In [141]:
def checkIfBernsteinVazirani(outputs):
    sLength = np.int8(np.log2(len(outputs)))
    assert 2**sLength == len(outputs)
    s = np.array([np.byte(outputs[2**i]) for i in range(0,sLength)], dtype=np.byte)
    s = np.flip(s)
    print(f"s={s}")
    table = truthTable(s)
    table["given"] = [np.byte(c) for c in outputs]
    print(table)
    return all(table["f(x)"] == table["given"])

In [142]:
checkIfBernsteinVazirani("0001")

s=[0 0]
        x      s  f(x)  given
0  (0, 0)  [0 0]     0      0
1  (0, 1)  [0 0]     0      0
2  (1, 0)  [0 0]     0      0
3  (1, 1)  [0 0]     0      1

False

In [145]:
checkIfBernsteinVazirani("01101001011010010110100101101001")

s=[0 0 1 1 1]
                  x            s  f(x)  given
0   (0, 0, 0, 0, 0)  [0 0 1 1 1]     0      0
1   (0, 0, 0, 0, 1)  [0 0 1 1 1]     1      1
2   (0, 0, 0, 1, 0)  [0 0 1 1 1]     1      1
3   (0, 0, 0, 1, 1)  [0 0 1 1 1]     0      0
4   (0, 0, 1, 0, 0)  [0 0 1 1 1]     1      1
5   (0, 0, 1, 0, 1)  [0 0 1 1 1]     0      0
6   (0, 0, 1, 1, 0)  [0 0 1 1 1]     0      0
7   (0, 0, 1, 1, 1)  [0 0 1 1 1]     1      1
8   (0, 1, 0, 0, 0)  [0 0 1 1 1]     0      0
9   (0, 1, 0, 0, 1)  [0 0 1 1 1]     1      1
10  (0, 1, 0, 1, 0)  [0 0 1 1 1]     1      1
11  (0, 1, 0, 1, 1)  [0 0 1 1 1]     0      0
12  (0, 1, 1, 0, 0)  [0 0 1 1 1]     1      1
13  (0, 1, 1, 0, 1)  [0 0 1 1 1]     0      0
14  (0, 1, 1, 1, 0)  [0 0 1 1 1]     0      0
15  (0, 1, 1, 1, 1)  [0 0 1 1 1]     1      1
16  (1, 0, 0, 0, 0)  [0 0 1 1 1]     0      0
17  (1, 0, 0, 0, 1)  [0 0 1 1 1]     1      1
18  (1, 0, 0, 1, 0)  [0 0 1 1 1]     1      1
19  (1, 0, 0, 1, 1)  [0 0 1 1 1]     0      0
20  (1, 0, 1, 0, 0)  [0 0 1 1 1]     1      1
21  (1, 0, 1, 0, 1)  [0 0 1 1 1]     0      0
22  (1, 0, 1, 1, 0)  [0 0 1 1 1]     0      0
23  (1, 0, 1, 1, 1)  [0 0 1 1 1]     1      1
24  (1, 1, 0, 0, 0)  [0 0 1 1 1]     0      0
25  (1, 1, 0, 0, 1)  [0 0 1 1 1]     1      1
26  (1, 1, 0, 1, 0)  [0 0 1 1 1]     1      1
27  (1, 1, 0, 1, 1)  [0 0 1 1 1]     0      0
28  (1, 1, 1, 0, 0)  [0 0 1 1 1]     1      1
29  (1, 1, 1, 0, 1)  [0 0 1 1 1]     0      0
30  (1, 1, 1, 1, 0)  [0 0 1 1 1]     0      0
31  (1, 1, 1, 1, 1)  [0 0 1 1 1]     1      1

True